import { defineConfig } from "vite-plus";

const ignorePatterns = [
  "**/node_modules/**",
  "**/dist/**",
  "**/.tanstack/**",
  "apps/client/src/routeTree.gen.ts",
  "packages/db/src/generated/**",
  // Generated by varlock from .env.schema.
  "apps/*/src/env.ts",
  // Third-party agent skills (managed by `vpx skills`, see skills-lock.json).
  ".agents/**",
  ".claude/skills/**",
  "agent/**",
  "skills-lock.json",
];

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: { ignorePatterns, sortPackageJson: true },
  lint: {
    ignorePatterns,
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
  run: {
    cache: true,
  },
});
